//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opm_validation_service {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CheckResultDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CheckResultDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("opm_validation_service.CheckResultDescriptions", typeof(CheckResultDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAN/EIC not recognized (code should start with 85 or 27).
        /// </summary>
        internal static string CodePrefixInvalid {
            get {
                return ResourceManager.GetString("CodePrefixInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAN code is invalid. Only digits are valid characters..
        /// </summary>
        internal static string EanInvalidCharacter {
            get {
                return ResourceManager.GetString("EanInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAN code is invalid. The check character is incorrect..
        /// </summary>
        internal static string EanInvalidCheckCharacter {
            get {
                return ResourceManager.GetString("EanInvalidCheckCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAN code has to have the length of 18 characters..
        /// </summary>
        internal static string EanInvalidLength {
            get {
                return ResourceManager.GetString("EanInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAN code is ok..
        /// </summary>
        internal static string EanOk {
            get {
                return ResourceManager.GetString("EanOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIC code is invalid. Only 0-9, A-Z and &apos;-&apos; are valid characters..
        /// </summary>
        internal static string EicInvalidCharacter {
            get {
                return ResourceManager.GetString("EicInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIC code is invalid. The check character  is incorrect..
        /// </summary>
        internal static string EicInvalidCheckCharacter {
            get {
                return ResourceManager.GetString("EicInvalidCheckCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIC code has to have the length of 16 characters..
        /// </summary>
        internal static string EicInvalidLength {
            get {
                return ResourceManager.GetString("EicInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIC code is ok..
        /// </summary>
        internal static string EicOk {
            get {
                return ResourceManager.GetString("EicOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No code supplied..
        /// </summary>
        internal static string NoCodeSupplied {
            get {
                return ResourceManager.GetString("NoCodeSupplied", resourceCulture);
            }
        }
    }
}
